# Generated by Django 5.2.6 on 2026-05-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('temperatura_dht', models.FloatField()),
                ('humedad_ambiente', models.FloatField()),
                ('temperatura_bmp', models.FloatField()),
                ('presion', models.IntegerField()),
                ('humedad_suelo', models.FloatField()),
                ('estado_suelo', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lectura de Sensor',
                'verbose_name_plural': 'Lecturas de Sensores',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
